name: ${project.parent.name}
main: com.chujian.dungeonsByCJ.DungeonsXL
version: ${project.parent.version}${buildNo}
authors: [Chujian]
description: ${project.parent.description}
website: ${project.parent.url}
depend: [ItemsXL]
softdepend: [CommandsXL, ItemsXL, Vault, Citizens, CustomMobs, InsaneMobs, MythicMobs, HolographicDisplays, LWC, PlaceholderAPI, Parties]
commands:
  dungeonsxl:
    description: DungeonsByCJ 的参考命令。
    aliases: [dcj,dungeon]
api-version: 1.13
